spring:
  application:
    name: discovery-service

server:
  port: ${SERVER_PORT:8761}

eureka:
  instance:
    hostname: ${EUREKA_HOST:localhost}
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: "${EUREKA_DEFAULT_ZONE:http://${eureka.instance.hostname}:${server.port}/eureka/}"
  server:
    enable-self-preservation: ${EUREKA_SELF_PRESERVATION:true}
    eviction-interval-timer-in-ms: ${EUREKA_EVICTION_INTERVAL_MS:60000}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
